// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'es-ES'],
  firebaseConfig: {
    apiKey: 'AIzaSyC7FQ36DoWH0xenPzMDcErPsvOmsjrG2Ko',
    authDomain: 'character-logbook.firebaseapp.com',
    projectId: 'character-logbook',
    storageBucket: 'character-logbook.appspot.com',
    messagingSenderId: '947515236319',
    appId: '1:947515236319:web:8b68ba2e7bd265c7ea2e6a',
  },
};
